# Generated by Django 5.0.7 on 2024-10-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentData',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Datetime')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
            ],
            options={
                'verbose_name': 'Environment Data',
                'verbose_name_plural': 'Environment Data',
                'db_table': 'environment',
                'managed': False,
            },
        ),
    ]
