# Generated by Django 5.0.7 on 2024-08-24 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureHumidityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_humidity_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temperature and Humidity Data',
                'verbose_name_plural': 'Temperature and Humidity Data',
                'db_table': 'temperature_humidity_data',
            },
        ),
    ]
