# Generated by Django 5.0.7 on 2024-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_temperaturehumiditydata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturehumiditydata',
            options={'verbose_name': 'Temperature, Humidity, and Sound Data', 'verbose_name_plural': 'Temperature, Humidity, and Sound Data'},
        ),
        migrations.AddField(
            model_name='temperaturehumiditydata',
            name='sound_state',
            field=models.CharField(choices=[('happiness', 'Happiness'), ('sadness', 'Sadness'), ('hungry', 'Hungry')], default='quiet', max_length=10, verbose_name='Sound State'),
        ),
    ]
