# Generated by Django 5.0.7 on 2024-10-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_environmentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusData',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Datetime')),
                ('crying', models.CharField(verbose_name='Crying')),
            ],
            options={
                'verbose_name': 'Status Data',
                'verbose_name_plural': 'Status Data',
                'db_table': 'status',
                'managed': False,
            },
        ),
    ]
