# Generated by Django 5.0.7 on 2024-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_statusdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovingStatusData',
            fields=[
                ('datetime', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Datetime')),
                ('state', models.CharField(verbose_name='State')),
            ],
            options={
                'verbose_name': 'Moving Status Data',
                'verbose_name_plural': 'Moving Status Data',
                'db_table': 'sleeping',
                'managed': False,
            },
        ),
    ]
